export enum Topics {
  Noun = 'noun',
  Pronoun = 'pronoun',
  Clothes = 'clothes',
  Conjunctions = 'conjunctions',
  Adjectives = 'adjectives',
  Places = 'places',
  Adverbs = 'adverbs',
  Family = 'family',
  Weather = 'weather',
  House = 'house',
  Body = 'body',
  Food = 'food',
  Prepositions = 'prepositions',
  Salutations = 'salutations',
  Calendar = 'calendar',
  Numbers = 'numbers',
  Colors = 'colors',
  Verbs = 'verbs',
  Expressions = 'expressions',
  Animals = 'animals',
  Plants = 'plants',
  Jobs = 'jobs',
  School = 'school',
  Grammar = 'grammar',
  Shapes = 'shapes',
  Sports = 'sports',
  Literature = 'literature',
  Earth = 'earth',
  Vehicles = 'vehicles',
  Business = 'business',
  Faith = 'faith',
  People = 'people',
  Justice = 'justice',
  Technology = 'technology',
}

export enum Gender {
  Female = 'female',
  Male = 'male',
  Neutral = 'neutral',
}
